name: Generate Terraform README docs
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '*.md'
      - '.github/workflows/documentation.yml'

permissions: {}

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@aeae0038ed47a547e0c0fca5c059d3335f48fb25 # v1.3.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "false"

    - name: Run Signed Commit Action
      uses: ministryofjustice/modernisation-platform-github-actions/signed-commit@14db114ed50a5ab565c3a134cf9efac0627e75e6 # v2.0.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
